bases:
- ../../base
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bgd1
    path: bgd-deployment.yaml
  - target:
      version: v1
      group: route.openshift.io
      kind: Route
      name: bgd1
      namespace: bgd1
    path: bgd-route.yaml
