bases:
- ../../base
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bgd2
    path: bgd-deployment.yaml
  - target:
      version: v1
      group: route.openshift.io
      kind: Route
      name: bgd2
      namespace: bgd2
    path: bgd-route.yaml
